//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CardModel
{
	public CardSuit Suit;
	public CardValue Value;

	public CardModel (CardSuit suit, CardValue value)
	{
		Suit = suit;
		Value = value;
	}

    public int GetBlackJackCardValue()
    {
        switch (Value)
        {
            case CardValue.two:
                return 2;
            case CardValue.three:
                return 3;
            case CardValue.four:
                return 4;
            case CardValue.five:
                return 5;
            case CardValue.six:
                return 6;
            case CardValue.seven:
                return 7;
            case CardValue.eight:
                return 8;
            case CardValue.nine:
                return 9;
            case CardValue.ten:
                return 10;
            case CardValue.Jack:
                return 10;
            case CardValue.Queen:
                return 10;
            case CardValue.King:
                return 10;
            case CardValue.Ace:
                return 1;
            default:
                Debug.Log("BAD DATA INPUT");
                return 0;
        }
    }
}


